language: objective-c
osx_image: xcode8
script: - xcodebuild clean build -workspace iOS/Tesseract-OCR-iOS.xcworkspace -scheme Template Framework Project -destination "platform=iOS Simulation,name=iPhone 6S"
